---
language: python

python:
  - '3.5'

matrix:
  include:
    - os: linux
      dist: xenial

before_install:
  - sudo apt update

install:
  - sudo apt install -y python3-pip python3-setuptools
  - sudo python3 -m pip install --upgrade pip setuptools wheel

before_script:
  - chmod +x docthis.sh

script:
  - ./docthis.sh
